version: '3'
services:
  #网关
  #自定义的服务名称
  evol-shenyu-gateway:
    build:
      context: evol-shenyu-gateway
      dockerfile: Dockerfile
    #镜像名称
    image: evol-shenyu-gateway:v1
    #容器名称
    container_name: evol-shenyu-gateway
    #容器down掉后，会自动重启
    restart: on-failure
    #映射端口。格式为宿主机端口：容器端口
    ports:
      - "9000:9000"
    #容器启动后，执行的命令
    command: java -Djava.security.egd=file:/dev/./urandom -jar /microservice/evol-shenyu-gateway-1.0.jar
    #授权服务
  evol-auth-server:
    build:
      context: evol-auth-server
      dockerfile: Dockerfile
    image: evol-auth-server:v1
    container_name: evol-auth-server
    restart: always
    ports:
      - "8090:8090"
    command: java -Djava.security.egd=file:/dev/./urandom -jar /microservice/evol-auth-server-1.0-SNAPSHOT.jar
    depends_on:
      - evol-shenyu-gateway
    links:
      - evol-shenyu-gateway:evol-shenyu-gateway
    #商户服务
  evol-business-server:
    build:
      context: evol-business-server
      dockerfile: Dockerfile
    image: evol-business-server:v1
    container_name: evol-business-server
    restart: always
    ports:
      - "8088:8088"
    command: java -Djava.security.egd=file:/dev/./urandom -jar /microservice/evol-business-server-1.0-SNAPSHOT.jar
    depends_on:
      - evol-shenyu-gateway
    links:
      - evol-shenyu-gateway:evol-shenyu-gateway
    #订单服务
  evol-order-server:
    build:
      context: evol-order-server
      dockerfile: Dockerfile
    image: evol-order-server:v1
    container_name: evol-order-server
    restart: always
    ports:
      - "8084:8084"
    command: java -Djava.security.egd=file:/dev/./urandom -jar /microservice/evol-order-server-1.0-SNAPSHOT.jar
    depends_on:
      - evol-shenyu-gateway
    links:
      - evol-shenyu-gateway:evol-shenyu-gateway
    #用户服务
  evol-user-server:
    build:
      context: evol-user-server
      dockerfile: Dockerfile
    image: evol-user-server:v1
    container_name: evol-user-server
    restart: always
    ports:
      - "8089:8089"
    command: java -Djava.security.egd=file:/dev/./urandom -jar /microservice/evol-user-server-1.0-SNAPSHOT.jar
    depends_on:
      - evol-shenyu-gateway
    links:
      - evol-shenyu-gateway:evol-shenyu-gateway