version: '3'
services:
  #网关
  #自定义的服务名称
  evol-web-client:
    build:
      context: evol-web/evol-web-client/src/docker
      dockerfile: Dockerfile
    #镜像名称
    image: evol-web-client:v1
    #容器名称
    container_name: evol-web-client
    #容器down掉后，会自动重启
    restart: on-failure
    #映射端口。格式为宿主机端口：容器端口
    ports:
      - "8090:8090"
    #容器启动后，执行的命令
    command: java -Djava.security.egd=file:/dev/./urandom -jar /microservice/evol-soul-gateway-1.0.jar
    #授权服务
  evol-web-manage:
    build:
      context: evol-web/evol-web-manage/src/docker
      dockerfile: Dockerfile
    image: evol-web-manage:v1
    container_name: evol-web-manage
    restart: on-failure
    ports:
      - "80:80"
    command: java -Djava.security.egd=file:/dev/./urandom -jar /microservice/evol-web-manage-1.0-SNAPSHOT.jar