server:
  port: 8080
spring:
  application:
    name: bjnews-and-jwt
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/game?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    database: 1

mybatis:
  type-aliases-package: com.codecow.bjnews.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

wechat:
  appId: #自己公司公众号 APPID
  secretKey: #自己公司公众号 secretKey
  firstCodeRedirectUrl: http://localhost:8080/OAuth/getOAuth    # 上线把 localhost:8080 改成上线域名 例：http://www.baidu.con/OAuth/getOAuth
  loginCodeRedirectUrl: http://localhost:8080/OAuth/getOAuth  # 上线把 localhost:8080 改成上线域名 例：http://www.baidu.con/OAuth/getOAuth

jwt:
  config:
    outTime: 18144000000 #一个月 60000 #一分钟
    securityKey: qazwsxedcrfvtgbyhn


