spring:
  application:
    name: springboot admin

server:
  port: 8001
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@127.0.0.1:8761/eureka/
    enabled: true
    register-with-eureka: true
    fetch-registry: true