spring:
  application:
    name: evol-pay-server
  redis:
    host: 127.0.0.1
    port: 6379
    password:
  zipkin:
    base-url: http://192.168.0.30:9411/

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@127.0.0.1:8761/eureka/
    enabled: true
    register-with-eureka: true
    fetch-registry: true